//! Render the portfolio as a single static HTML file.
//!
//! No framework, no network, no JavaScript — inline CSS only, so the
//! output is one self-contained file that opens anywhere and works
//! offline. [`render`] is pure (roadmaps in, HTML string out) so it is
//! trivially testable; the CLI handles reading files and writing output.

use std::fmt::Write as _;

use crate::model::{Maturity, Roadmap, Status};

/// One project to render: its parsed roadmap plus where it lives on disk.
pub struct Entry<'a> {
    pub roadmap: &'a Roadmap,
    pub repo_path: &'a str,
}

/// Render the whole portfolio report as an HTML document.
pub fn render(entries: &[Entry]) -> String {
    let mut cards = String::new();
    for entry in entries {
        render_card(&mut cards, entry);
    }

    let count = entries.len();
    let subtitle = match count {
        0 => "No projects registered yet.".to_string(),
        1 => "1 project".to_string(),
        n => format!("{n} projects"),
    };

    format!(
        "<!DOCTYPE html>\n\
<html lang=\"en\">\n<head>\n\
<meta charset=\"utf-8\">\n\
<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
<title>Orchestrator — portfolio</title>\n\
<style>{CSS}</style>\n\
</head>\n<body>\n\
<header class=\"top\">\n\
  <h1>Portfolio</h1>\n\
  <p class=\"subtitle\">{subtitle}</p>\n\
</header>\n\
<main class=\"grid\">\n{cards}</main>\n\
<footer class=\"foot\">Generated by Orchestrator — read-mostly, local-first.</footer>\n\
</body>\n</html>\n",
        subtitle = escape(&subtitle),
        cards = cards,
    )
}

fn render_card(out: &mut String, entry: &Entry) {
    let rm = entry.roadmap;
    let prog = rm.progress();
    let pct = prog.percent.round() as i64;

    let _ = writeln!(
        out,
        "  <section class=\"card\">\n\
    <div class=\"card-head\">\n\
      <h2>{name}</h2>\n\
      <span class=\"badge badge-{mat_class}\">{mat}</span>\n\
    </div>\n\
    <p class=\"repo\">{repo}</p>\n\
    <div class=\"bar\" role=\"img\" aria-label=\"{done} of {total} phases done\">\n\
      <div class=\"bar-fill\" style=\"width:{pct}%\"></div>\n\
    </div>\n\
    <p class=\"prog\">{done}/{total} phases · {pct}%</p>\n\
    <ol class=\"phases\">",
        name = escape(&rm.project.name),
        mat = escape(maturity_label(rm.project.maturity)),
        mat_class = maturity_class(rm.project.maturity),
        repo = escape(rm.project.repo.as_str()),
        done = prog.done,
        total = prog.total,
        pct = pct,
    );

    for phase in &rm.phases {
        let _ = writeln!(
            out,
            "      <li class=\"ph ph-{cls}\"><span class=\"dot\">{marker}</span>{name}</li>",
            cls = status_class(phase.status),
            marker = status_marker(phase.status),
            name = escape(&phase.name),
        );
    }

    out.push_str("    </ol>\n");

    if !rm.parked.is_empty() {
        out.push_str("    <p class=\"parked\">Parked: ");
        let names: Vec<String> = rm.parked.iter().map(|p| escape(&p.name)).collect();
        out.push_str(&names.join(", "));
        out.push_str("</p>\n");
    }

    out.push_str("  </section>\n");
}

fn maturity_label(m: Maturity) -> &'static str {
    match m {
        Maturity::Idea => "idea",
        Maturity::Prototype => "prototype",
        Maturity::Working => "working",
        Maturity::Production => "production",
    }
}

fn maturity_class(m: Maturity) -> &'static str {
    maturity_label(m) // labels are already valid class suffixes
}

fn status_class(s: Status) -> &'static str {
    match s {
        Status::Done => "done",
        Status::InProgress => "wip",
        Status::Blocked => "blocked",
        Status::Todo => "todo",
    }
}

fn status_marker(s: Status) -> &'static str {
    match s {
        Status::Done => "✓",
        Status::InProgress => "▸",
        Status::Blocked => "✗",
        Status::Todo => "·",
    }
}

/// Minimal HTML escaping for text placed in element content / attributes.
fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(ch),
        }
    }
    out
}

const CSS: &str = "\
:root{--bg:#f6f7f9;--card:#fff;--ink:#1b1f24;--muted:#6b7280;--line:#e5e7eb;\
--bar:#e5e7eb;--fill:#2563eb;--done:#16a34a;--wip:#2563eb;--blocked:#dc2626;--todo:#9ca3af}\
@media(prefers-color-scheme:dark){:root{--bg:#0d1117;--card:#161b22;--ink:#e6edf3;\
--muted:#9198a1;--line:#30363d;--bar:#30363d;--fill:#388bfd;--done:#3fb950;--wip:#388bfd;\
--blocked:#f85149;--todo:#6e7681}}\
*{box-sizing:border-box}\
body{margin:0;padding:32px 20px 48px;background:var(--bg);color:var(--ink);\
font:15px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif}\
.top{max-width:1000px;margin:0 auto 24px}\
.top h1{margin:0;font-size:26px}\
.subtitle{margin:4px 0 0;color:var(--muted)}\
.grid{max-width:1000px;margin:0 auto;display:grid;gap:16px;\
grid-template-columns:repeat(auto-fill,minmax(300px,1fr))}\
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:18px 18px 16px}\
.card-head{display:flex;align-items:center;justify-content:space-between;gap:8px}\
.card-head h2{margin:0;font-size:17px}\
.repo{margin:2px 0 12px;color:var(--muted);font-size:13px;font-family:ui-monospace,Menlo,Consolas,monospace}\
.badge{font-size:11px;text-transform:uppercase;letter-spacing:.04em;padding:3px 8px;border-radius:999px;\
border:1px solid var(--line);color:var(--muted);white-space:nowrap}\
.badge-working{color:var(--done);border-color:var(--done)}\
.badge-production{color:#fff;background:var(--done);border-color:var(--done)}\
.badge-prototype{color:var(--wip);border-color:var(--wip)}\
.bar{height:8px;background:var(--bar);border-radius:999px;overflow:hidden}\
.bar-fill{height:100%;background:var(--fill);border-radius:999px}\
.prog{margin:8px 0 12px;font-size:13px;color:var(--muted)}\
.phases{list-style:none;margin:0;padding:0}\
.ph{display:flex;gap:8px;align-items:baseline;padding:3px 0;font-size:14px}\
.ph .dot{width:1em;text-align:center;color:var(--todo)}\
.ph-done .dot{color:var(--done)}.ph-done{color:var(--muted)}\
.ph-wip .dot{color:var(--wip)}.ph-wip{font-weight:600}\
.ph-blocked .dot{color:var(--blocked)}\
.parked{margin:10px 0 0;font-size:12px;color:var(--muted);border-top:1px dashed var(--line);padding-top:8px}\
.foot{max-width:1000px;margin:28px auto 0;color:var(--muted);font-size:12px}\
";
